### PR TITLE
Home Page Form - Current State

### PR DESCRIPTION
**Pull request by JohnJBarrett22**
Initial push of form on the home page for review and feedback, corrections coming on the next push.

### CODE REVIEW

**Review by suba-krishnan — COMMENTED** [review]
Looks good but make the following changes in the UI please

- Remove colon from (cities to compare text)
- Center all headings
- Adjust the font size for heading (bigger than the rest) 
- Align the toggle tokens ( 3 * 3)
- Low end/high end placeholders in grey/smaller font size
- Include app name, tag line and placeholder for image (I'll upload the image shortly).
- Optimize for desktop and mobile view
- Rent textbox should only accept numbers and not both. 
- Rename Submit to Search

**Comment by jona70x** [comment]
Good start. Nice that you have divided the sections, and the form contains all data from the prototype except for the bedrooms list. Here are my suggestions:

For the city and amenity selection, I would recommend you use input(checkboxes) and style them as toggle tokens. This will give you flexibility and control to manage the form data with React hooks. You can use a combination of <span><input type='checkbox'> to wrap the checkboxes and assign the classes dynamically (using the state hook) to make it look like a toggle token.
 
For the rent section, the only change I suggest is to change the type to a number and add a min value (0).

For the styling, I am also new to tailwind, but if you want to make things responsive here's the link to check the resources https://tailwindcss.com/docs/responsive-design. Something that helped was remembering that tailwind is mobile-first, so we are basically styling for mobile, and everything passed the midpoint becomes the 'Desktop version'. 

Also, because you are using the Layout component and the Search Container, you might have some styling issues because the layout is already a flexbox. Check my last pull request to see how I structured the routes that way we don't have to use a Container nor Layout. The only thing is you have to center the form, but it will give your more flexibility.

**Comment by rinilkunhiraman** [comment]
https://github.com/chingu-voyages/v40-bears-team-34/pull/20 Take this as a reference

**Review by suba-krishnan — COMMENTED** [review]
Make the text 'pick cities ....' the same size/format as Apartment Features
Minimum 2 in brackets (Minimum 2)
Reduce the width of Search button to normal button size

**Review by rmcguire6 — CHANGES_REQUESTED** [review]
I would put a minimum value in both the rent check boxes so that they don't allow a negative value. Also, $1 seems too low for a monthly rent anywhere, but I'm not sure what we should set as the minimum. I know you have code that needs to get pushed for the amenities selectors. Otherwise it looks great. And @0xengineeer has code in the dev branch that will need to be merged in.

**Pull request merged**
